// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: loader.proto
// Original file comments:
// *
// Copyright Soramitsu Co., Ltd. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
#ifndef GRPC_loader_2eproto__INCLUDED
#define GRPC_loader_2eproto__INCLUDED

#include "loader.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace iroha {
namespace network {
namespace proto {

class Loader final {
 public:
  static constexpr char const* service_full_name() {
    return "iroha.network.proto.Loader";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::iroha::protocol::Block>> retrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::iroha::protocol::Block>>(retrieveBlocksRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::iroha::protocol::Block>> AsyncretrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::iroha::protocol::Block>>(AsyncretrieveBlocksRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::iroha::protocol::Block>> PrepareAsyncretrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::iroha::protocol::Block>>(PrepareAsyncretrieveBlocksRaw(context, request, cq));
    }
    virtual ::grpc::Status retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::iroha::protocol::Block* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iroha::protocol::Block>> AsyncretrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iroha::protocol::Block>>(AsyncretrieveBlockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iroha::protocol::Block>> PrepareAsyncretrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::iroha::protocol::Block>>(PrepareAsyncretrieveBlockRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void retrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::grpc::ClientReadReactor< ::iroha::protocol::Block>* reactor) = 0;
      #else
      virtual void retrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::grpc::experimental::ClientReadReactor< ::iroha::protocol::Block>* reactor) = 0;
      #endif
      virtual void retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::iroha::protocol::Block>* retrieveBlocksRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::iroha::protocol::Block>* AsyncretrieveBlocksRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::iroha::protocol::Block>* PrepareAsyncretrieveBlocksRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::iroha::protocol::Block>* AsyncretrieveBlockRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::iroha::protocol::Block>* PrepareAsyncretrieveBlockRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::iroha::protocol::Block>> retrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::iroha::protocol::Block>>(retrieveBlocksRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::iroha::protocol::Block>> AsyncretrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::iroha::protocol::Block>>(AsyncretrieveBlocksRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::iroha::protocol::Block>> PrepareAsyncretrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::iroha::protocol::Block>>(PrepareAsyncretrieveBlocksRaw(context, request, cq));
    }
    ::grpc::Status retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::iroha::protocol::Block* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iroha::protocol::Block>> AsyncretrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iroha::protocol::Block>>(AsyncretrieveBlockRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iroha::protocol::Block>> PrepareAsyncretrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::iroha::protocol::Block>>(PrepareAsyncretrieveBlockRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void retrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::grpc::ClientReadReactor< ::iroha::protocol::Block>* reactor) override;
      #else
      void retrieveBlocks(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::grpc::experimental::ClientReadReactor< ::iroha::protocol::Block>* reactor) override;
      #endif
      void retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void retrieveBlock(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::iroha::protocol::Block>* retrieveBlocksRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request) override;
    ::grpc::ClientAsyncReader< ::iroha::protocol::Block>* AsyncretrieveBlocksRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::iroha::protocol::Block>* PrepareAsyncretrieveBlocksRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::iroha::protocol::Block>* AsyncretrieveBlockRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::iroha::protocol::Block>* PrepareAsyncretrieveBlockRaw(::grpc::ClientContext* context, const ::iroha::network::proto::BlockRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_retrieveBlocks_;
    const ::grpc::internal::RpcMethod rpcmethod_retrieveBlock_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status retrieveBlocks(::grpc::ServerContext* context, const ::iroha::network::proto::BlockRequest* request, ::grpc::ServerWriter< ::iroha::protocol::Block>* writer);
    virtual ::grpc::Status retrieveBlock(::grpc::ServerContext* context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_retrieveBlocks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_retrieveBlocks() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_retrieveBlocks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlocks(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::grpc::ServerWriter< ::iroha::protocol::Block>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestretrieveBlocks(::grpc::ServerContext* context, ::iroha::network::proto::BlockRequest* request, ::grpc::ServerAsyncWriter< ::iroha::protocol::Block>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_retrieveBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_retrieveBlock() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_retrieveBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlock(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestretrieveBlock(::grpc::ServerContext* context, ::iroha::network::proto::BlockRequest* request, ::grpc::ServerAsyncResponseWriter< ::iroha::protocol::Block>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_retrieveBlocks<WithAsyncMethod_retrieveBlock<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_retrieveBlocks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_retrieveBlocks() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::iroha::network::proto::BlockRequest* request) { return this->retrieveBlocks(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_retrieveBlocks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlocks(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::grpc::ServerWriter< ::iroha::protocol::Block>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::iroha::protocol::Block>* retrieveBlocks(
      ::grpc::CallbackServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::iroha::protocol::Block>* retrieveBlocks(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_retrieveBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_retrieveBlock() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::iroha::network::proto::BlockRequest* request, ::iroha::protocol::Block* response) { return this->retrieveBlock(context, request, response); }));}
    void SetMessageAllocatorFor_retrieveBlock(
        ::grpc::experimental::MessageAllocator< ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_retrieveBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlock(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* retrieveBlock(
      ::grpc::CallbackServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* retrieveBlock(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_retrieveBlocks<ExperimentalWithCallbackMethod_retrieveBlock<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_retrieveBlocks<ExperimentalWithCallbackMethod_retrieveBlock<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_retrieveBlocks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_retrieveBlocks() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_retrieveBlocks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlocks(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::grpc::ServerWriter< ::iroha::protocol::Block>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_retrieveBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_retrieveBlock() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_retrieveBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlock(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_retrieveBlocks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_retrieveBlocks() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_retrieveBlocks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlocks(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::grpc::ServerWriter< ::iroha::protocol::Block>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestretrieveBlocks(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_retrieveBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_retrieveBlock() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_retrieveBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlock(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestretrieveBlock(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_retrieveBlocks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_retrieveBlocks() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->retrieveBlocks(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_retrieveBlocks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlocks(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::grpc::ServerWriter< ::iroha::protocol::Block>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* retrieveBlocks(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* retrieveBlocks(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_retrieveBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_retrieveBlock() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->retrieveBlock(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_retrieveBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status retrieveBlock(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* retrieveBlock(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* retrieveBlock(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_retrieveBlock : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_retrieveBlock() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>* streamer) {
                       return this->StreamedretrieveBlock(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_retrieveBlock() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status retrieveBlock(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::iroha::protocol::Block* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedretrieveBlock(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::iroha::network::proto::BlockRequest,::iroha::protocol::Block>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_retrieveBlock<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_retrieveBlocks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_retrieveBlocks() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::iroha::network::proto::BlockRequest, ::iroha::protocol::Block>* streamer) {
                       return this->StreamedretrieveBlocks(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_retrieveBlocks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status retrieveBlocks(::grpc::ServerContext* /*context*/, const ::iroha::network::proto::BlockRequest* /*request*/, ::grpc::ServerWriter< ::iroha::protocol::Block>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedretrieveBlocks(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::iroha::network::proto::BlockRequest,::iroha::protocol::Block>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_retrieveBlocks<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_retrieveBlocks<WithStreamedUnaryMethod_retrieveBlock<Service > > StreamedService;
};

}  // namespace proto
}  // namespace network
}  // namespace iroha


#endif  // GRPC_loader_2eproto__INCLUDED
