// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yac.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yac_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yac_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yac_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yac_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yac_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_yac_2eproto_metadata_getter(int index);
namespace iroha {
namespace consensus {
namespace yac {
namespace proto {
class Hash;
struct HashDefaultTypeInternal;
extern HashDefaultTypeInternal _Hash_default_instance_;
class Signature;
struct SignatureDefaultTypeInternal;
extern SignatureDefaultTypeInternal _Signature_default_instance_;
class State;
struct StateDefaultTypeInternal;
extern StateDefaultTypeInternal _State_default_instance_;
class Vote;
struct VoteDefaultTypeInternal;
extern VoteDefaultTypeInternal _Vote_default_instance_;
class VoteHashes;
struct VoteHashesDefaultTypeInternal;
extern VoteHashesDefaultTypeInternal _VoteHashes_default_instance_;
class VoteRound;
struct VoteRoundDefaultTypeInternal;
extern VoteRoundDefaultTypeInternal _VoteRound_default_instance_;
}  // namespace proto
}  // namespace yac
}  // namespace consensus
}  // namespace iroha
PROTOBUF_NAMESPACE_OPEN
template<> ::iroha::consensus::yac::proto::Hash* Arena::CreateMaybeMessage<::iroha::consensus::yac::proto::Hash>(Arena*);
template<> ::iroha::consensus::yac::proto::Signature* Arena::CreateMaybeMessage<::iroha::consensus::yac::proto::Signature>(Arena*);
template<> ::iroha::consensus::yac::proto::State* Arena::CreateMaybeMessage<::iroha::consensus::yac::proto::State>(Arena*);
template<> ::iroha::consensus::yac::proto::Vote* Arena::CreateMaybeMessage<::iroha::consensus::yac::proto::Vote>(Arena*);
template<> ::iroha::consensus::yac::proto::VoteHashes* Arena::CreateMaybeMessage<::iroha::consensus::yac::proto::VoteHashes>(Arena*);
template<> ::iroha::consensus::yac::proto::VoteRound* Arena::CreateMaybeMessage<::iroha::consensus::yac::proto::VoteRound>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace iroha {
namespace consensus {
namespace yac {
namespace proto {

// ===================================================================

class Signature PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iroha.consensus.yac.proto.Signature) */ {
 public:
  inline Signature() : Signature(nullptr) {}
  virtual ~Signature();
  explicit constexpr Signature(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Signature(const Signature& from);
  Signature(Signature&& from) noexcept
    : Signature() {
    *this = ::std::move(from);
  }

  inline Signature& operator=(const Signature& from) {
    CopyFrom(from);
    return *this;
  }
  inline Signature& operator=(Signature&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Signature& default_instance() {
    return *internal_default_instance();
  }
  static inline const Signature* internal_default_instance() {
    return reinterpret_cast<const Signature*>(
               &_Signature_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Signature& a, Signature& b) {
    a.Swap(&b);
  }
  inline void Swap(Signature* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Signature* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Signature* New() const final {
    return CreateMaybeMessage<Signature>(nullptr);
  }

  Signature* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Signature>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Signature& from);
  void MergeFrom(const Signature& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Signature* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iroha.consensus.yac.proto.Signature";
  }
  protected:
  explicit Signature(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_yac_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPubkeyFieldNumber = 1,
    kSignatureFieldNumber = 2,
  };
  // bytes pubkey = 1;
  void clear_pubkey();
  const std::string& pubkey() const;
  void set_pubkey(const std::string& value);
  void set_pubkey(std::string&& value);
  void set_pubkey(const char* value);
  void set_pubkey(const void* value, size_t size);
  std::string* mutable_pubkey();
  std::string* release_pubkey();
  void set_allocated_pubkey(std::string* pubkey);
  private:
  const std::string& _internal_pubkey() const;
  void _internal_set_pubkey(const std::string& value);
  std::string* _internal_mutable_pubkey();
  public:

  // bytes signature = 2;
  void clear_signature();
  const std::string& signature() const;
  void set_signature(const std::string& value);
  void set_signature(std::string&& value);
  void set_signature(const char* value);
  void set_signature(const void* value, size_t size);
  std::string* mutable_signature();
  std::string* release_signature();
  void set_allocated_signature(std::string* signature);
  private:
  const std::string& _internal_signature() const;
  void _internal_set_signature(const std::string& value);
  std::string* _internal_mutable_signature();
  public:

  // @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Signature)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pubkey_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr signature_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yac_2eproto;
};
// -------------------------------------------------------------------

class VoteRound PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iroha.consensus.yac.proto.VoteRound) */ {
 public:
  inline VoteRound() : VoteRound(nullptr) {}
  virtual ~VoteRound();
  explicit constexpr VoteRound(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VoteRound(const VoteRound& from);
  VoteRound(VoteRound&& from) noexcept
    : VoteRound() {
    *this = ::std::move(from);
  }

  inline VoteRound& operator=(const VoteRound& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoteRound& operator=(VoteRound&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VoteRound& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoteRound* internal_default_instance() {
    return reinterpret_cast<const VoteRound*>(
               &_VoteRound_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(VoteRound& a, VoteRound& b) {
    a.Swap(&b);
  }
  inline void Swap(VoteRound* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoteRound* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VoteRound* New() const final {
    return CreateMaybeMessage<VoteRound>(nullptr);
  }

  VoteRound* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VoteRound>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VoteRound& from);
  void MergeFrom(const VoteRound& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VoteRound* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iroha.consensus.yac.proto.VoteRound";
  }
  protected:
  explicit VoteRound(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_yac_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockRoundFieldNumber = 1,
    kRejectRoundFieldNumber = 2,
  };
  // uint64 block_round = 1;
  void clear_block_round();
  ::PROTOBUF_NAMESPACE_ID::uint64 block_round() const;
  void set_block_round(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_block_round() const;
  void _internal_set_block_round(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 reject_round = 2;
  void clear_reject_round();
  ::PROTOBUF_NAMESPACE_ID::uint32 reject_round() const;
  void set_reject_round(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_reject_round() const;
  void _internal_set_reject_round(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.VoteRound)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint64 block_round_;
  ::PROTOBUF_NAMESPACE_ID::uint32 reject_round_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yac_2eproto;
};
// -------------------------------------------------------------------

class VoteHashes PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iroha.consensus.yac.proto.VoteHashes) */ {
 public:
  inline VoteHashes() : VoteHashes(nullptr) {}
  virtual ~VoteHashes();
  explicit constexpr VoteHashes(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VoteHashes(const VoteHashes& from);
  VoteHashes(VoteHashes&& from) noexcept
    : VoteHashes() {
    *this = ::std::move(from);
  }

  inline VoteHashes& operator=(const VoteHashes& from) {
    CopyFrom(from);
    return *this;
  }
  inline VoteHashes& operator=(VoteHashes&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const VoteHashes& default_instance() {
    return *internal_default_instance();
  }
  static inline const VoteHashes* internal_default_instance() {
    return reinterpret_cast<const VoteHashes*>(
               &_VoteHashes_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(VoteHashes& a, VoteHashes& b) {
    a.Swap(&b);
  }
  inline void Swap(VoteHashes* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VoteHashes* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline VoteHashes* New() const final {
    return CreateMaybeMessage<VoteHashes>(nullptr);
  }

  VoteHashes* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<VoteHashes>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const VoteHashes& from);
  void MergeFrom(const VoteHashes& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VoteHashes* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iroha.consensus.yac.proto.VoteHashes";
  }
  protected:
  explicit VoteHashes(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_yac_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProposalFieldNumber = 1,
    kBlockFieldNumber = 2,
  };
  // bytes proposal = 1;
  void clear_proposal();
  const std::string& proposal() const;
  void set_proposal(const std::string& value);
  void set_proposal(std::string&& value);
  void set_proposal(const char* value);
  void set_proposal(const void* value, size_t size);
  std::string* mutable_proposal();
  std::string* release_proposal();
  void set_allocated_proposal(std::string* proposal);
  private:
  const std::string& _internal_proposal() const;
  void _internal_set_proposal(const std::string& value);
  std::string* _internal_mutable_proposal();
  public:

  // bytes block = 2;
  void clear_block();
  const std::string& block() const;
  void set_block(const std::string& value);
  void set_block(std::string&& value);
  void set_block(const char* value);
  void set_block(const void* value, size_t size);
  std::string* mutable_block();
  std::string* release_block();
  void set_allocated_block(std::string* block);
  private:
  const std::string& _internal_block() const;
  void _internal_set_block(const std::string& value);
  std::string* _internal_mutable_block();
  public:

  // @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.VoteHashes)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr proposal_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr block_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yac_2eproto;
};
// -------------------------------------------------------------------

class Hash PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iroha.consensus.yac.proto.Hash) */ {
 public:
  inline Hash() : Hash(nullptr) {}
  virtual ~Hash();
  explicit constexpr Hash(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Hash(const Hash& from);
  Hash(Hash&& from) noexcept
    : Hash() {
    *this = ::std::move(from);
  }

  inline Hash& operator=(const Hash& from) {
    CopyFrom(from);
    return *this;
  }
  inline Hash& operator=(Hash&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Hash& default_instance() {
    return *internal_default_instance();
  }
  static inline const Hash* internal_default_instance() {
    return reinterpret_cast<const Hash*>(
               &_Hash_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Hash& a, Hash& b) {
    a.Swap(&b);
  }
  inline void Swap(Hash* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Hash* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Hash* New() const final {
    return CreateMaybeMessage<Hash>(nullptr);
  }

  Hash* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Hash>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Hash& from);
  void MergeFrom(const Hash& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Hash* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iroha.consensus.yac.proto.Hash";
  }
  protected:
  explicit Hash(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_yac_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVoteRoundFieldNumber = 1,
    kVoteHashesFieldNumber = 2,
    kBlockSignatureFieldNumber = 3,
  };
  // .iroha.consensus.yac.proto.VoteRound vote_round = 1;
  bool has_vote_round() const;
  private:
  bool _internal_has_vote_round() const;
  public:
  void clear_vote_round();
  const ::iroha::consensus::yac::proto::VoteRound& vote_round() const;
  ::iroha::consensus::yac::proto::VoteRound* release_vote_round();
  ::iroha::consensus::yac::proto::VoteRound* mutable_vote_round();
  void set_allocated_vote_round(::iroha::consensus::yac::proto::VoteRound* vote_round);
  private:
  const ::iroha::consensus::yac::proto::VoteRound& _internal_vote_round() const;
  ::iroha::consensus::yac::proto::VoteRound* _internal_mutable_vote_round();
  public:
  void unsafe_arena_set_allocated_vote_round(
      ::iroha::consensus::yac::proto::VoteRound* vote_round);
  ::iroha::consensus::yac::proto::VoteRound* unsafe_arena_release_vote_round();

  // .iroha.consensus.yac.proto.VoteHashes vote_hashes = 2;
  bool has_vote_hashes() const;
  private:
  bool _internal_has_vote_hashes() const;
  public:
  void clear_vote_hashes();
  const ::iroha::consensus::yac::proto::VoteHashes& vote_hashes() const;
  ::iroha::consensus::yac::proto::VoteHashes* release_vote_hashes();
  ::iroha::consensus::yac::proto::VoteHashes* mutable_vote_hashes();
  void set_allocated_vote_hashes(::iroha::consensus::yac::proto::VoteHashes* vote_hashes);
  private:
  const ::iroha::consensus::yac::proto::VoteHashes& _internal_vote_hashes() const;
  ::iroha::consensus::yac::proto::VoteHashes* _internal_mutable_vote_hashes();
  public:
  void unsafe_arena_set_allocated_vote_hashes(
      ::iroha::consensus::yac::proto::VoteHashes* vote_hashes);
  ::iroha::consensus::yac::proto::VoteHashes* unsafe_arena_release_vote_hashes();

  // .iroha.consensus.yac.proto.Signature block_signature = 3;
  bool has_block_signature() const;
  private:
  bool _internal_has_block_signature() const;
  public:
  void clear_block_signature();
  const ::iroha::consensus::yac::proto::Signature& block_signature() const;
  ::iroha::consensus::yac::proto::Signature* release_block_signature();
  ::iroha::consensus::yac::proto::Signature* mutable_block_signature();
  void set_allocated_block_signature(::iroha::consensus::yac::proto::Signature* block_signature);
  private:
  const ::iroha::consensus::yac::proto::Signature& _internal_block_signature() const;
  ::iroha::consensus::yac::proto::Signature* _internal_mutable_block_signature();
  public:
  void unsafe_arena_set_allocated_block_signature(
      ::iroha::consensus::yac::proto::Signature* block_signature);
  ::iroha::consensus::yac::proto::Signature* unsafe_arena_release_block_signature();

  // @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Hash)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::iroha::consensus::yac::proto::VoteRound* vote_round_;
  ::iroha::consensus::yac::proto::VoteHashes* vote_hashes_;
  ::iroha::consensus::yac::proto::Signature* block_signature_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yac_2eproto;
};
// -------------------------------------------------------------------

class Vote PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iroha.consensus.yac.proto.Vote) */ {
 public:
  inline Vote() : Vote(nullptr) {}
  virtual ~Vote();
  explicit constexpr Vote(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vote(const Vote& from);
  Vote(Vote&& from) noexcept
    : Vote() {
    *this = ::std::move(from);
  }

  inline Vote& operator=(const Vote& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vote& operator=(Vote&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Vote& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vote* internal_default_instance() {
    return reinterpret_cast<const Vote*>(
               &_Vote_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Vote& a, Vote& b) {
    a.Swap(&b);
  }
  inline void Swap(Vote* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vote* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Vote* New() const final {
    return CreateMaybeMessage<Vote>(nullptr);
  }

  Vote* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Vote>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Vote& from);
  void MergeFrom(const Vote& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vote* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iroha.consensus.yac.proto.Vote";
  }
  protected:
  explicit Vote(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_yac_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHashFieldNumber = 1,
    kSignatureFieldNumber = 2,
  };
  // .iroha.consensus.yac.proto.Hash hash = 1;
  bool has_hash() const;
  private:
  bool _internal_has_hash() const;
  public:
  void clear_hash();
  const ::iroha::consensus::yac::proto::Hash& hash() const;
  ::iroha::consensus::yac::proto::Hash* release_hash();
  ::iroha::consensus::yac::proto::Hash* mutable_hash();
  void set_allocated_hash(::iroha::consensus::yac::proto::Hash* hash);
  private:
  const ::iroha::consensus::yac::proto::Hash& _internal_hash() const;
  ::iroha::consensus::yac::proto::Hash* _internal_mutable_hash();
  public:
  void unsafe_arena_set_allocated_hash(
      ::iroha::consensus::yac::proto::Hash* hash);
  ::iroha::consensus::yac::proto::Hash* unsafe_arena_release_hash();

  // .iroha.consensus.yac.proto.Signature signature = 2;
  bool has_signature() const;
  private:
  bool _internal_has_signature() const;
  public:
  void clear_signature();
  const ::iroha::consensus::yac::proto::Signature& signature() const;
  ::iroha::consensus::yac::proto::Signature* release_signature();
  ::iroha::consensus::yac::proto::Signature* mutable_signature();
  void set_allocated_signature(::iroha::consensus::yac::proto::Signature* signature);
  private:
  const ::iroha::consensus::yac::proto::Signature& _internal_signature() const;
  ::iroha::consensus::yac::proto::Signature* _internal_mutable_signature();
  public:
  void unsafe_arena_set_allocated_signature(
      ::iroha::consensus::yac::proto::Signature* signature);
  ::iroha::consensus::yac::proto::Signature* unsafe_arena_release_signature();

  // @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.Vote)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::iroha::consensus::yac::proto::Hash* hash_;
  ::iroha::consensus::yac::proto::Signature* signature_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yac_2eproto;
};
// -------------------------------------------------------------------

class State PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:iroha.consensus.yac.proto.State) */ {
 public:
  inline State() : State(nullptr) {}
  virtual ~State();
  explicit constexpr State(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  State(const State& from);
  State(State&& from) noexcept
    : State() {
    *this = ::std::move(from);
  }

  inline State& operator=(const State& from) {
    CopyFrom(from);
    return *this;
  }
  inline State& operator=(State&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const State& default_instance() {
    return *internal_default_instance();
  }
  static inline const State* internal_default_instance() {
    return reinterpret_cast<const State*>(
               &_State_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(State& a, State& b) {
    a.Swap(&b);
  }
  inline void Swap(State* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(State* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline State* New() const final {
    return CreateMaybeMessage<State>(nullptr);
  }

  State* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<State>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const State& from);
  void MergeFrom(const State& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(State* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "iroha.consensus.yac.proto.State";
  }
  protected:
  explicit State(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_yac_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVotesFieldNumber = 1,
  };
  // repeated .iroha.consensus.yac.proto.Vote votes = 1;
  int votes_size() const;
  private:
  int _internal_votes_size() const;
  public:
  void clear_votes();
  ::iroha::consensus::yac::proto::Vote* mutable_votes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::iroha::consensus::yac::proto::Vote >*
      mutable_votes();
  private:
  const ::iroha::consensus::yac::proto::Vote& _internal_votes(int index) const;
  ::iroha::consensus::yac::proto::Vote* _internal_add_votes();
  public:
  const ::iroha::consensus::yac::proto::Vote& votes(int index) const;
  ::iroha::consensus::yac::proto::Vote* add_votes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::iroha::consensus::yac::proto::Vote >&
      votes() const;

  // @@protoc_insertion_point(class_scope:iroha.consensus.yac.proto.State)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::iroha::consensus::yac::proto::Vote > votes_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_yac_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Signature

// bytes pubkey = 1;
inline void Signature::clear_pubkey() {
  pubkey_.ClearToEmpty();
}
inline const std::string& Signature::pubkey() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.Signature.pubkey)
  return _internal_pubkey();
}
inline void Signature::set_pubkey(const std::string& value) {
  _internal_set_pubkey(value);
  // @@protoc_insertion_point(field_set:iroha.consensus.yac.proto.Signature.pubkey)
}
inline std::string* Signature::mutable_pubkey() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.Signature.pubkey)
  return _internal_mutable_pubkey();
}
inline const std::string& Signature::_internal_pubkey() const {
  return pubkey_.Get();
}
inline void Signature::_internal_set_pubkey(const std::string& value) {
  
  pubkey_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Signature::set_pubkey(std::string&& value) {
  
  pubkey_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:iroha.consensus.yac.proto.Signature.pubkey)
}
inline void Signature::set_pubkey(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pubkey_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:iroha.consensus.yac.proto.Signature.pubkey)
}
inline void Signature::set_pubkey(const void* value,
    size_t size) {
  
  pubkey_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:iroha.consensus.yac.proto.Signature.pubkey)
}
inline std::string* Signature::_internal_mutable_pubkey() {
  
  return pubkey_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Signature::release_pubkey() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.Signature.pubkey)
  return pubkey_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Signature::set_allocated_pubkey(std::string* pubkey) {
  if (pubkey != nullptr) {
    
  } else {
    
  }
  pubkey_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pubkey,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.Signature.pubkey)
}

// bytes signature = 2;
inline void Signature::clear_signature() {
  signature_.ClearToEmpty();
}
inline const std::string& Signature::signature() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.Signature.signature)
  return _internal_signature();
}
inline void Signature::set_signature(const std::string& value) {
  _internal_set_signature(value);
  // @@protoc_insertion_point(field_set:iroha.consensus.yac.proto.Signature.signature)
}
inline std::string* Signature::mutable_signature() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.Signature.signature)
  return _internal_mutable_signature();
}
inline const std::string& Signature::_internal_signature() const {
  return signature_.Get();
}
inline void Signature::_internal_set_signature(const std::string& value) {
  
  signature_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Signature::set_signature(std::string&& value) {
  
  signature_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:iroha.consensus.yac.proto.Signature.signature)
}
inline void Signature::set_signature(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  signature_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:iroha.consensus.yac.proto.Signature.signature)
}
inline void Signature::set_signature(const void* value,
    size_t size) {
  
  signature_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:iroha.consensus.yac.proto.Signature.signature)
}
inline std::string* Signature::_internal_mutable_signature() {
  
  return signature_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Signature::release_signature() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.Signature.signature)
  return signature_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Signature::set_allocated_signature(std::string* signature) {
  if (signature != nullptr) {
    
  } else {
    
  }
  signature_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), signature,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.Signature.signature)
}

// -------------------------------------------------------------------

// VoteRound

// uint64 block_round = 1;
inline void VoteRound::clear_block_round() {
  block_round_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 VoteRound::_internal_block_round() const {
  return block_round_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 VoteRound::block_round() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.VoteRound.block_round)
  return _internal_block_round();
}
inline void VoteRound::_internal_set_block_round(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  block_round_ = value;
}
inline void VoteRound::set_block_round(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_block_round(value);
  // @@protoc_insertion_point(field_set:iroha.consensus.yac.proto.VoteRound.block_round)
}

// uint32 reject_round = 2;
inline void VoteRound::clear_reject_round() {
  reject_round_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 VoteRound::_internal_reject_round() const {
  return reject_round_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 VoteRound::reject_round() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.VoteRound.reject_round)
  return _internal_reject_round();
}
inline void VoteRound::_internal_set_reject_round(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  reject_round_ = value;
}
inline void VoteRound::set_reject_round(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_reject_round(value);
  // @@protoc_insertion_point(field_set:iroha.consensus.yac.proto.VoteRound.reject_round)
}

// -------------------------------------------------------------------

// VoteHashes

// bytes proposal = 1;
inline void VoteHashes::clear_proposal() {
  proposal_.ClearToEmpty();
}
inline const std::string& VoteHashes::proposal() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.VoteHashes.proposal)
  return _internal_proposal();
}
inline void VoteHashes::set_proposal(const std::string& value) {
  _internal_set_proposal(value);
  // @@protoc_insertion_point(field_set:iroha.consensus.yac.proto.VoteHashes.proposal)
}
inline std::string* VoteHashes::mutable_proposal() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.VoteHashes.proposal)
  return _internal_mutable_proposal();
}
inline const std::string& VoteHashes::_internal_proposal() const {
  return proposal_.Get();
}
inline void VoteHashes::_internal_set_proposal(const std::string& value) {
  
  proposal_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void VoteHashes::set_proposal(std::string&& value) {
  
  proposal_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:iroha.consensus.yac.proto.VoteHashes.proposal)
}
inline void VoteHashes::set_proposal(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  proposal_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:iroha.consensus.yac.proto.VoteHashes.proposal)
}
inline void VoteHashes::set_proposal(const void* value,
    size_t size) {
  
  proposal_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:iroha.consensus.yac.proto.VoteHashes.proposal)
}
inline std::string* VoteHashes::_internal_mutable_proposal() {
  
  return proposal_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* VoteHashes::release_proposal() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.VoteHashes.proposal)
  return proposal_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VoteHashes::set_allocated_proposal(std::string* proposal) {
  if (proposal != nullptr) {
    
  } else {
    
  }
  proposal_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), proposal,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.VoteHashes.proposal)
}

// bytes block = 2;
inline void VoteHashes::clear_block() {
  block_.ClearToEmpty();
}
inline const std::string& VoteHashes::block() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.VoteHashes.block)
  return _internal_block();
}
inline void VoteHashes::set_block(const std::string& value) {
  _internal_set_block(value);
  // @@protoc_insertion_point(field_set:iroha.consensus.yac.proto.VoteHashes.block)
}
inline std::string* VoteHashes::mutable_block() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.VoteHashes.block)
  return _internal_mutable_block();
}
inline const std::string& VoteHashes::_internal_block() const {
  return block_.Get();
}
inline void VoteHashes::_internal_set_block(const std::string& value) {
  
  block_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void VoteHashes::set_block(std::string&& value) {
  
  block_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:iroha.consensus.yac.proto.VoteHashes.block)
}
inline void VoteHashes::set_block(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  block_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:iroha.consensus.yac.proto.VoteHashes.block)
}
inline void VoteHashes::set_block(const void* value,
    size_t size) {
  
  block_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:iroha.consensus.yac.proto.VoteHashes.block)
}
inline std::string* VoteHashes::_internal_mutable_block() {
  
  return block_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* VoteHashes::release_block() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.VoteHashes.block)
  return block_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void VoteHashes::set_allocated_block(std::string* block) {
  if (block != nullptr) {
    
  } else {
    
  }
  block_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), block,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.VoteHashes.block)
}

// -------------------------------------------------------------------

// Hash

// .iroha.consensus.yac.proto.VoteRound vote_round = 1;
inline bool Hash::_internal_has_vote_round() const {
  return this != internal_default_instance() && vote_round_ != nullptr;
}
inline bool Hash::has_vote_round() const {
  return _internal_has_vote_round();
}
inline void Hash::clear_vote_round() {
  if (GetArena() == nullptr && vote_round_ != nullptr) {
    delete vote_round_;
  }
  vote_round_ = nullptr;
}
inline const ::iroha::consensus::yac::proto::VoteRound& Hash::_internal_vote_round() const {
  const ::iroha::consensus::yac::proto::VoteRound* p = vote_round_;
  return p != nullptr ? *p : reinterpret_cast<const ::iroha::consensus::yac::proto::VoteRound&>(
      ::iroha::consensus::yac::proto::_VoteRound_default_instance_);
}
inline const ::iroha::consensus::yac::proto::VoteRound& Hash::vote_round() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.Hash.vote_round)
  return _internal_vote_round();
}
inline void Hash::unsafe_arena_set_allocated_vote_round(
    ::iroha::consensus::yac::proto::VoteRound* vote_round) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vote_round_);
  }
  vote_round_ = vote_round;
  if (vote_round) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:iroha.consensus.yac.proto.Hash.vote_round)
}
inline ::iroha::consensus::yac::proto::VoteRound* Hash::release_vote_round() {
  
  ::iroha::consensus::yac::proto::VoteRound* temp = vote_round_;
  vote_round_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::iroha::consensus::yac::proto::VoteRound* Hash::unsafe_arena_release_vote_round() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.Hash.vote_round)
  
  ::iroha::consensus::yac::proto::VoteRound* temp = vote_round_;
  vote_round_ = nullptr;
  return temp;
}
inline ::iroha::consensus::yac::proto::VoteRound* Hash::_internal_mutable_vote_round() {
  
  if (vote_round_ == nullptr) {
    auto* p = CreateMaybeMessage<::iroha::consensus::yac::proto::VoteRound>(GetArena());
    vote_round_ = p;
  }
  return vote_round_;
}
inline ::iroha::consensus::yac::proto::VoteRound* Hash::mutable_vote_round() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.Hash.vote_round)
  return _internal_mutable_vote_round();
}
inline void Hash::set_allocated_vote_round(::iroha::consensus::yac::proto::VoteRound* vote_round) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete vote_round_;
  }
  if (vote_round) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(vote_round);
    if (message_arena != submessage_arena) {
      vote_round = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vote_round, submessage_arena);
    }
    
  } else {
    
  }
  vote_round_ = vote_round;
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.Hash.vote_round)
}

// .iroha.consensus.yac.proto.VoteHashes vote_hashes = 2;
inline bool Hash::_internal_has_vote_hashes() const {
  return this != internal_default_instance() && vote_hashes_ != nullptr;
}
inline bool Hash::has_vote_hashes() const {
  return _internal_has_vote_hashes();
}
inline void Hash::clear_vote_hashes() {
  if (GetArena() == nullptr && vote_hashes_ != nullptr) {
    delete vote_hashes_;
  }
  vote_hashes_ = nullptr;
}
inline const ::iroha::consensus::yac::proto::VoteHashes& Hash::_internal_vote_hashes() const {
  const ::iroha::consensus::yac::proto::VoteHashes* p = vote_hashes_;
  return p != nullptr ? *p : reinterpret_cast<const ::iroha::consensus::yac::proto::VoteHashes&>(
      ::iroha::consensus::yac::proto::_VoteHashes_default_instance_);
}
inline const ::iroha::consensus::yac::proto::VoteHashes& Hash::vote_hashes() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.Hash.vote_hashes)
  return _internal_vote_hashes();
}
inline void Hash::unsafe_arena_set_allocated_vote_hashes(
    ::iroha::consensus::yac::proto::VoteHashes* vote_hashes) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vote_hashes_);
  }
  vote_hashes_ = vote_hashes;
  if (vote_hashes) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:iroha.consensus.yac.proto.Hash.vote_hashes)
}
inline ::iroha::consensus::yac::proto::VoteHashes* Hash::release_vote_hashes() {
  
  ::iroha::consensus::yac::proto::VoteHashes* temp = vote_hashes_;
  vote_hashes_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::iroha::consensus::yac::proto::VoteHashes* Hash::unsafe_arena_release_vote_hashes() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.Hash.vote_hashes)
  
  ::iroha::consensus::yac::proto::VoteHashes* temp = vote_hashes_;
  vote_hashes_ = nullptr;
  return temp;
}
inline ::iroha::consensus::yac::proto::VoteHashes* Hash::_internal_mutable_vote_hashes() {
  
  if (vote_hashes_ == nullptr) {
    auto* p = CreateMaybeMessage<::iroha::consensus::yac::proto::VoteHashes>(GetArena());
    vote_hashes_ = p;
  }
  return vote_hashes_;
}
inline ::iroha::consensus::yac::proto::VoteHashes* Hash::mutable_vote_hashes() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.Hash.vote_hashes)
  return _internal_mutable_vote_hashes();
}
inline void Hash::set_allocated_vote_hashes(::iroha::consensus::yac::proto::VoteHashes* vote_hashes) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete vote_hashes_;
  }
  if (vote_hashes) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(vote_hashes);
    if (message_arena != submessage_arena) {
      vote_hashes = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vote_hashes, submessage_arena);
    }
    
  } else {
    
  }
  vote_hashes_ = vote_hashes;
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.Hash.vote_hashes)
}

// .iroha.consensus.yac.proto.Signature block_signature = 3;
inline bool Hash::_internal_has_block_signature() const {
  return this != internal_default_instance() && block_signature_ != nullptr;
}
inline bool Hash::has_block_signature() const {
  return _internal_has_block_signature();
}
inline void Hash::clear_block_signature() {
  if (GetArena() == nullptr && block_signature_ != nullptr) {
    delete block_signature_;
  }
  block_signature_ = nullptr;
}
inline const ::iroha::consensus::yac::proto::Signature& Hash::_internal_block_signature() const {
  const ::iroha::consensus::yac::proto::Signature* p = block_signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::iroha::consensus::yac::proto::Signature&>(
      ::iroha::consensus::yac::proto::_Signature_default_instance_);
}
inline const ::iroha::consensus::yac::proto::Signature& Hash::block_signature() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.Hash.block_signature)
  return _internal_block_signature();
}
inline void Hash::unsafe_arena_set_allocated_block_signature(
    ::iroha::consensus::yac::proto::Signature* block_signature) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(block_signature_);
  }
  block_signature_ = block_signature;
  if (block_signature) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:iroha.consensus.yac.proto.Hash.block_signature)
}
inline ::iroha::consensus::yac::proto::Signature* Hash::release_block_signature() {
  
  ::iroha::consensus::yac::proto::Signature* temp = block_signature_;
  block_signature_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::iroha::consensus::yac::proto::Signature* Hash::unsafe_arena_release_block_signature() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.Hash.block_signature)
  
  ::iroha::consensus::yac::proto::Signature* temp = block_signature_;
  block_signature_ = nullptr;
  return temp;
}
inline ::iroha::consensus::yac::proto::Signature* Hash::_internal_mutable_block_signature() {
  
  if (block_signature_ == nullptr) {
    auto* p = CreateMaybeMessage<::iroha::consensus::yac::proto::Signature>(GetArena());
    block_signature_ = p;
  }
  return block_signature_;
}
inline ::iroha::consensus::yac::proto::Signature* Hash::mutable_block_signature() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.Hash.block_signature)
  return _internal_mutable_block_signature();
}
inline void Hash::set_allocated_block_signature(::iroha::consensus::yac::proto::Signature* block_signature) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete block_signature_;
  }
  if (block_signature) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(block_signature);
    if (message_arena != submessage_arena) {
      block_signature = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, block_signature, submessage_arena);
    }
    
  } else {
    
  }
  block_signature_ = block_signature;
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.Hash.block_signature)
}

// -------------------------------------------------------------------

// Vote

// .iroha.consensus.yac.proto.Hash hash = 1;
inline bool Vote::_internal_has_hash() const {
  return this != internal_default_instance() && hash_ != nullptr;
}
inline bool Vote::has_hash() const {
  return _internal_has_hash();
}
inline void Vote::clear_hash() {
  if (GetArena() == nullptr && hash_ != nullptr) {
    delete hash_;
  }
  hash_ = nullptr;
}
inline const ::iroha::consensus::yac::proto::Hash& Vote::_internal_hash() const {
  const ::iroha::consensus::yac::proto::Hash* p = hash_;
  return p != nullptr ? *p : reinterpret_cast<const ::iroha::consensus::yac::proto::Hash&>(
      ::iroha::consensus::yac::proto::_Hash_default_instance_);
}
inline const ::iroha::consensus::yac::proto::Hash& Vote::hash() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.Vote.hash)
  return _internal_hash();
}
inline void Vote::unsafe_arena_set_allocated_hash(
    ::iroha::consensus::yac::proto::Hash* hash) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(hash_);
  }
  hash_ = hash;
  if (hash) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:iroha.consensus.yac.proto.Vote.hash)
}
inline ::iroha::consensus::yac::proto::Hash* Vote::release_hash() {
  
  ::iroha::consensus::yac::proto::Hash* temp = hash_;
  hash_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::iroha::consensus::yac::proto::Hash* Vote::unsafe_arena_release_hash() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.Vote.hash)
  
  ::iroha::consensus::yac::proto::Hash* temp = hash_;
  hash_ = nullptr;
  return temp;
}
inline ::iroha::consensus::yac::proto::Hash* Vote::_internal_mutable_hash() {
  
  if (hash_ == nullptr) {
    auto* p = CreateMaybeMessage<::iroha::consensus::yac::proto::Hash>(GetArena());
    hash_ = p;
  }
  return hash_;
}
inline ::iroha::consensus::yac::proto::Hash* Vote::mutable_hash() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.Vote.hash)
  return _internal_mutable_hash();
}
inline void Vote::set_allocated_hash(::iroha::consensus::yac::proto::Hash* hash) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete hash_;
  }
  if (hash) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(hash);
    if (message_arena != submessage_arena) {
      hash = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, hash, submessage_arena);
    }
    
  } else {
    
  }
  hash_ = hash;
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.Vote.hash)
}

// .iroha.consensus.yac.proto.Signature signature = 2;
inline bool Vote::_internal_has_signature() const {
  return this != internal_default_instance() && signature_ != nullptr;
}
inline bool Vote::has_signature() const {
  return _internal_has_signature();
}
inline void Vote::clear_signature() {
  if (GetArena() == nullptr && signature_ != nullptr) {
    delete signature_;
  }
  signature_ = nullptr;
}
inline const ::iroha::consensus::yac::proto::Signature& Vote::_internal_signature() const {
  const ::iroha::consensus::yac::proto::Signature* p = signature_;
  return p != nullptr ? *p : reinterpret_cast<const ::iroha::consensus::yac::proto::Signature&>(
      ::iroha::consensus::yac::proto::_Signature_default_instance_);
}
inline const ::iroha::consensus::yac::proto::Signature& Vote::signature() const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.Vote.signature)
  return _internal_signature();
}
inline void Vote::unsafe_arena_set_allocated_signature(
    ::iroha::consensus::yac::proto::Signature* signature) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(signature_);
  }
  signature_ = signature;
  if (signature) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:iroha.consensus.yac.proto.Vote.signature)
}
inline ::iroha::consensus::yac::proto::Signature* Vote::release_signature() {
  
  ::iroha::consensus::yac::proto::Signature* temp = signature_;
  signature_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::iroha::consensus::yac::proto::Signature* Vote::unsafe_arena_release_signature() {
  // @@protoc_insertion_point(field_release:iroha.consensus.yac.proto.Vote.signature)
  
  ::iroha::consensus::yac::proto::Signature* temp = signature_;
  signature_ = nullptr;
  return temp;
}
inline ::iroha::consensus::yac::proto::Signature* Vote::_internal_mutable_signature() {
  
  if (signature_ == nullptr) {
    auto* p = CreateMaybeMessage<::iroha::consensus::yac::proto::Signature>(GetArena());
    signature_ = p;
  }
  return signature_;
}
inline ::iroha::consensus::yac::proto::Signature* Vote::mutable_signature() {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.Vote.signature)
  return _internal_mutable_signature();
}
inline void Vote::set_allocated_signature(::iroha::consensus::yac::proto::Signature* signature) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete signature_;
  }
  if (signature) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(signature);
    if (message_arena != submessage_arena) {
      signature = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, signature, submessage_arena);
    }
    
  } else {
    
  }
  signature_ = signature;
  // @@protoc_insertion_point(field_set_allocated:iroha.consensus.yac.proto.Vote.signature)
}

// -------------------------------------------------------------------

// State

// repeated .iroha.consensus.yac.proto.Vote votes = 1;
inline int State::_internal_votes_size() const {
  return votes_.size();
}
inline int State::votes_size() const {
  return _internal_votes_size();
}
inline void State::clear_votes() {
  votes_.Clear();
}
inline ::iroha::consensus::yac::proto::Vote* State::mutable_votes(int index) {
  // @@protoc_insertion_point(field_mutable:iroha.consensus.yac.proto.State.votes)
  return votes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::iroha::consensus::yac::proto::Vote >*
State::mutable_votes() {
  // @@protoc_insertion_point(field_mutable_list:iroha.consensus.yac.proto.State.votes)
  return &votes_;
}
inline const ::iroha::consensus::yac::proto::Vote& State::_internal_votes(int index) const {
  return votes_.Get(index);
}
inline const ::iroha::consensus::yac::proto::Vote& State::votes(int index) const {
  // @@protoc_insertion_point(field_get:iroha.consensus.yac.proto.State.votes)
  return _internal_votes(index);
}
inline ::iroha::consensus::yac::proto::Vote* State::_internal_add_votes() {
  return votes_.Add();
}
inline ::iroha::consensus::yac::proto::Vote* State::add_votes() {
  // @@protoc_insertion_point(field_add:iroha.consensus.yac.proto.State.votes)
  return _internal_add_votes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::iroha::consensus::yac::proto::Vote >&
State::votes() const {
  // @@protoc_insertion_point(field_list:iroha.consensus.yac.proto.State.votes)
  return votes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace yac
}  // namespace consensus
}  // namespace iroha

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yac_2eproto
